#!/bin/sh

case "$1:$2" in
    post:suspend|post:hibernate|post:hybrid-sleep|post:suspend-then-hibernate)
        if command -v systemctl >/dev/null 2>&1; then
            systemctl --no-block try-restart logid.service >/dev/null 2>&1 || true
        fi
        ;;
esac
